@url = http://localhost:5000/users-module 
@email = user1@confab.io 
@password = secret 
@role = user 
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5MjljODA3YS03Nzg4LTQ4NDYtOWVjYy0zYWRkNGNjOTI5NDEiLCJ1bmlxdWVfbmFtZSI6IjkyOWM4MDdhLTc3ODgtNDg0Ni05ZWNjLTNhZGQ0Y2M5Mjk0MSIsImp0aSI6IjQwM2M1MzE2LTIzYjYtNGEyNy05MjAyLWI0NWNhYTNjMjgxMiIsImlhdCI6IjE2Njc3NTcxODY4MDMiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY2Nzc1NzE4NiwiZXhwIjoxNjY3NzYwNzg2LCJpc3MiOiJjb25mYWIifQ.zsf4_RGbg3GujYsJefwxOlb-NZ3V2Emct__uSBMXySc 

### 
GET {{url}}

### 
GET {{url}}/account 
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/account/sign-up 
Content-Type: application/json

{
	"email": "{{email}}", 
	"password": "{{password}}",
	"role": "{{role}}", 
	"claims": {
		"permissions": ["conferences", "hosts", "speakers", "tickets", "users"]
	}
}

### 
POST {{url}}/account/sign-in
Content-Type: application/json

{
	"email": "{{email}}", 
	"password": "{{password}}"
}