@url = http://localhost:5000/conferences-module 
@hostId = bf7f2b20-e039-43fd-8ba6-e1866e80cd17
@conferenceId = ec998970-e7b8-43d6-b891-a36a18ec5727
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5NzhkMmNmYi01ZWJkLTQyMWUtYWViNi0yYjlmZjBmY2I1YTciLCJ1bmlxdWVfbmFtZSI6Ijk3OGQyY2ZiLTVlYmQtNDIxZS1hZWI2LTJiOWZmMGZjYjVhNyIsImp0aSI6IjU1MmMyYmE2LTg4M2YtNDFjYS05M2I3LTJjM2Q0ZDk4YjUxMCIsImlhdCI6IjE2Njc1ODM3MTAxNjgiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY2NzU4MzcxMCwiZXhwIjoxNjY3NTg3MzEwLCJpc3MiOiJjb25mYWIifQ.0MHVWcn3PWzk1PI4UZfZbSh_DlA5ZmkoEVBdog34TkQ

### 
GET {{url}}

### 
POST {{url}}/hosts 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Host #1", 
	"description": "Lorem ipsum"
}

### 
GET {{url}}/hosts

### 
GET {{url}}/hosts/{{hostId}}

### 
PUT {{url}}/hosts/{{hostId}} 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Host #1"
}

### 
DELETE {{url}}/hosts/{{hostId}} 
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/conferences 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"hostId": "{{hostId}}", 
	"name": "Conference #1", 
	"description": "Lorem ipsum", 
	"location": "Test 123", 
	"from": "2021-05-01", 
	"to": "2021-05-02", 
	"participantsLimit": 100, 
	"logoUrl": null
}

### 
GET {{url}}/conferences

### 
GET {{url}}/conferences/{{conferenceId}}

### 
PUT {{url}}/conferences/{{conferenceId}} 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Conference #2", 
	"description": "Lorem ipsum", 
	"location": "Test 123", 
	"from": "2021-05-01", 
	"to": "2021-05-02", 
	"participantsLimit": 100, 
	"logoUrl": null
}

### 
DELETE {{url}}/conferences/{{conferenceId}} 
Authorization: Bearer {{accessToken}}