@url = http://localhost:5000/conferences-module 
@hostId = b5937797-6679-4025-b3c5-6ccb957758d9
@conferenceId = ec998970-e7b8-43d6-b891-a36a18ec5727
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0NTQzNTUyMi0yNmMwLTRiYWUtOTkwYy1lNTQ3ODQxYzAzNDUiLCJ1bmlxdWVfbmFtZSI6IjQ1NDM1NTIyLTI2YzAtNGJhZS05OTBjLWU1NDc4NDFjMDM0NSIsImp0aSI6ImMyMTVhZWYxLWM4ODktNDdlNi04MTk1LWViMDcxN2E1ZDQwNyIsImlhdCI6IjE2Njk0MTI4MTUwNzIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJ1c2VyIiwicGVybWlzc2lvbnMiOlsiY29uZmVyZW5jZXMiLCJob3N0cyIsInNwZWFrZXJzIiwidGlja2V0cyIsInVzZXJzIl0sIm5iZiI6MTY2OTQxMjgxNSwiZXhwIjoxNjY5NDE2NDE1LCJpc3MiOiJjb25mYWIifQ.QX-LpfMWMYkcWuLdIWic6OwjGYuD3RGxzM8Yq0ZyZcw

### 
GET {{url}}

### 
POST {{url}}/hosts 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Host #1", 
	"description": "Lorem ipsum"
}

### 
GET {{url}}/hosts

### 
GET {{url}}/hosts/{{hostId}}

### 
PUT {{url}}/hosts/{{hostId}} 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Host #1"
}

### 
DELETE {{url}}/hosts/{{hostId}} 
Authorization: Bearer {{accessToken}}

### 
POST {{url}}/conferences 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"hostId": "{{hostId}}", 
	"name": "Conference #1", 
	"description": "Lorem ipsum", 
	"location": "Test 123", 
	"from": "2021-05-01", 
	"to": "2021-05-02", 
	"participantsLimit": 100, 
	"logoUrl": null
}

### 
GET {{url}}/conferences

### 
GET {{url}}/conferences/{{conferenceId}}

### 
PUT {{url}}/conferences/{{conferenceId}} 
Authorization: Bearer {{accessToken}} 
Content-Type: application/json

{
	"name": "Conference #2", 
	"description": "Lorem ipsum", 
	"location": "Test 123", 
	"from": "2021-05-01", 
	"to": "2021-05-02", 
	"participantsLimit": 100, 
	"logoUrl": null
}

### 
DELETE {{url}}/conferences/{{conferenceId}} 
Authorization: Bearer {{accessToken}}